name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente à meia-noite UTC

  workflow_dispatch:  # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Gerar animação da cobrinha
        uses: Platane/snk@master
        with:
          github_user_name: Partakos
          outputs: dist/github-contribution-grid-snake.svg

      - name: Armazenar a animação
        uses: actions/upload-artifact@v4
        with:
          name: snake-animation
          path: dist/github-contribution-grid-snake.svg
